/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Russian
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 */
#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define MAPPER_D0D1                // For Cyrillic
#define DISPLAY_CHARSET_ISO10646_5

#define WELCOME_MSG                         MACHINE_NAME _UxGT("Anet A6 готов к работе!")
#define MSG_BACK                            _UxGT("НАЗАД")
#define MSG_SD_INSERTED                     _UxGT("Карта обнаружена")
#define MSG_SD_REMOVED                      _UxGT("Карта извлечена")
#define MSG_LCD_ENDSTOPS                    _UxGT("Концевики")
#define MSG_MAIN                            _UxGT("ГЛАВНОЕ МЕНЮ")
#define MSG_AUTOSTART                       _UxGT("Автозапуск")
#define MSG_DISABLE_STEPPERS                _UxGT("Отключить моторы")
#define MSG_DEBUG_MENU                      _UxGT("Отладочное меню")
#define MSG_PROGRESS_BAR_TEST               _UxGT("Тест индикатора")
#define MSG_AUTO_HOME                       _UxGT("Возврат в ноль")
#define MSG_AUTO_HOME_X                     _UxGT("Возврат X в ноль")
#define MSG_AUTO_HOME_Y                     _UxGT("Возврат Y в ноль")
#define MSG_AUTO_HOME_Z                     _UxGT("Возврат Z в ноль")
#define MSG_LEVEL_BED_HOMING                _UxGT("Запуск калибровки стола")
#define MSG_LEVEL_BED_WAITING               _UxGT("Идет калибровка стола...")
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("Следующая точка калибровки")
#define MSG_LEVEL_BED_DONE                  _UxGT("Калибровка стола завершена!")
#define MSG_Z_FADE_HEIGHT                   _UxGT("Спад высоты по Z")
#define MSG_SET_HOME_OFFSETS                _UxGT("Установить ноль")
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("Ноль установлен")
#define MSG_SET_ORIGIN                      _UxGT("Установить ноль")
#define MSG_PREHEAT_1                       _UxGT("Преднагрев PLA")
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" Полный")
#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" Хотэнд")
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" Стол")
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" Настроить")
#define MSG_PREHEAT_2                       _UxGT("Преднагрев ABS")
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" Полный")
#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" Хотэнд")
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" Стол")
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" Настроить")
#define MSG_COOLDOWN                        _UxGT("Отключчить нагрев")
#define MSG_SWITCH_PS_ON                    _UxGT("Включить электропитание")
#define MSG_SWITCH_PS_OFF                   _UxGT("Отключить электропитание")
#define MSG_EXTRUDE                         _UxGT("Выдавливание")
#define MSG_RETRACT                         _UxGT("Втягивание")
#define MSG_MOVE_AXIS                       _UxGT("Перемещения по осям")
#define MSG_BED_LEVELING                    _UxGT("Калибровка стола")
#define MSG_LEVEL_BED                       _UxGT("Калибровать стол")
#define MSG_EDITING_STOPPED                 _UxGT("Редактирование завершено")
#define MSG_USER_MENU                       _UxGT("Комманды пользователя")
#define MSG_UBL_DOING_G29                   _UxGT("UBL: выполняется G29")
#define MSG_UBL_UNHOMED                     _UxGT("UBL: возврат в ноль")
#define MSG_UBL_TOOLS                       _UxGT("UBL: инструменты")
#define MSG_UBL_LEVEL_BED                   _UxGT("UBL: калибровка стола")
#define MSG_UBL_MANUAL_MESH                 _UxGT("UBL: ручной режим")
#define MSG_UBL_BC_INSERT                   _UxGT("UBL: шимм и измер.")
#define MSG_UBL_BC_INSERT2                  _UxGT("UBL: измерение")
#define MSG_UBL_BC_REMOVE                   _UxGT("UBL: удал. измер.")
#define MSG_UBL_MOVING_TO_NEXT              _UxGT("UBL: движение дальше")
#define MSG_UBL_ACTIVATE_MESH               _UxGT("UBL: активировать сетку")
#define MSG_UBL_DEACTIVATE_MESH             _UxGT("UBL: деактивировать сетку")
#define MSG_UBL_SET_BED_TEMP                _UxGT("UBL: уст. темп. стола")
#define MSG_UBL_CUSTOM_BED_TEMP             MSG_UBL_SET_BED_TEMP
#define MSG_UBL_SET_HOTEND_TEMP             _UxGT("UBL: уст. темп. хотэнда")
#define MSG_UBL_CUSTOM_HOTEND_TEMP          MSG_UBL_SET_HOTEND_TEMP
#define MSG_UBL_MESH_EDIT                   _UxGT("UBL: редактор сеток")
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("UBL: сетка пользователя")
#define MSG_UBL_FINE_TUNE_MESH              _UxGT("UBL: точная настройка")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("UBL: ред. завершено")
#define MSG_UBL_BUILD_MESH_MENU             _UxGT("UBL: построение сеток")
#define MSG_UBL_BUILD_PLA_MESH              _UxGT("UBL: сетка PLA")
#define MSG_UBL_BUILD_ABS_MESH              _UxGT("UBL: сетка ABS")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("UBL: сетка пользователя")
#define MSG_UBL_BUILD_COLD_MESH             _UxGT("UBL: холодная сетка")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("UBL: уст. высоту сетки")
#define MSG_UBL_MESH_HEIGHT_AMOUNT          _UxGT("UBL: высота сетки")
#define MSG_UBL_VALIDATE_MESH_MENU          _UxGT("Проверить сетку")
#define MSG_UBL_VALIDATE_PLA_MESH           _UxGT("Проверить сетку PLA")
#define MSG_UBL_VALIDATE_ABS_MESH           _UxGT("Проверить сетку ABS")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("Проверить свою сетку")
#define MSG_UBL_CONTINUE_MESH               _UxGT("Продолжить сетку")
#define MSG_UBL_MESH_LEVELING               _UxGT("Калибровка сетки")
#define MSG_UBL_3POINT_MESH_LEVELING        _UxGT("Калибровка 3-х точек")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("Калибровка растера")
#define MSG_UBL_MESH_LEVEL                  _UxGT("Выровнить сетку")
#define MSG_UBL_SIDE_POINTS                 _UxGT("Крайние точки")
#define MSG_UBL_MAP_TYPE                    _UxGT("Тип карты")
#define MSG_UBL_OUTPUT_MAP                  _UxGT("Вывести карту сетки")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("Вывести на хост")
#define MSG_UBL_OUTPUT_MAP_CSV              _UxGT("Вывести в CSV")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("Забекапить сетку")
#define MSG_UBL_INFO_UBL                    _UxGT("Выдача инфор. UBL")
#define MSG_UBL_EDIT_MESH_MENU              _UxGT("Редактировать сетку")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("Заполнить значения")
#define MSG_UBL_MANUAL_FILLIN               _UxGT("Ручное заполнение")
#define MSG_UBL_SMART_FILLIN                _UxGT("Уменое заполнение")
#define MSG_UBL_FILLIN_MESH                 _UxGT("Заполнить сетку")
#define MSG_UBL_INVALIDATE_ALL              _UxGT("Аннулировать всё")
#define MSG_UBL_INVALIDATE_CLOSEST          _UxGT("Аннулир. ближ. точку")
#define MSG_UBL_FINE_TUNE_ALL               _UxGT("Точ. настройка всего")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("Настр. ближ. точки")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("Хранилище сетей")
#define MSG_UBL_STORAGE_SLOT                _UxGT("Слот памяти")
#define MSG_UBL_LOAD_MESH                   _UxGT("Загрузить стол сетки")
#define MSG_UBL_SAVE_MESH                   _UxGT("Сохранить стол сетки")
#define MSG_UBL_SAVE_ERROR                  _UxGT("Ошибка: Сохр. UBL")
#define MSG_UBL_RESTORE_ERROR               _UxGT("Ошибка: Загрузки UBL")
#define MSG_UBL_Z_OFFSET_STOPPED            _UxGT("Смещение Z останов.")
#define MSG_UBL_STEP_BY_STEP_MENU           _UxGT("Пошаговый UBL")
#define MSG_FREE_XY                         _UxGT("Освобождение XY")
#define MSG_MOVING                          _UxGT("Перемещение...")
#define MSG_MOVE_X                          _UxGT("Перемещение по X")
#define MSG_MOVE_Y                          _UxGT("Перемещение по Y")
#define MSG_MOVE_Z                          _UxGT("Перемещение по Z")
#define MSG_MOVE_E                          _UxGT("Выдавливание")
#define MSG_MOVE_01MM                       _UxGT("Шаг 0.1 мм")
#define MSG_MOVE_1MM                        _UxGT("Шаг 1 мм")
#define MSG_MOVE_10MM                       _UxGT("Шаг 1 см")
#define MSG_SPEED                           _UxGT("Скорость")
#define MSG_BED_Z                           _UxGT("Z стола")
#define MSG_NOZZLE                          LCD_STR_THERMOMETER _UxGT(" Хотэнд")
#define MSG_BED                             LCD_STR_THERMOMETER _UxGT(" Стол")
#define MSG_FAN_SPEED                       _UxGT("Кулер")
#define MSG_FLOW                            _UxGT("Поток")
#define MSG_CONTROL                         _UxGT("Настройки")
#define MSG_MIN                             LCD_STR_THERMOMETER _UxGT(" Минимум")
#define MSG_MAX                             LCD_STR_THERMOMETER _UxGT(" Максимум")
#define MSG_FACTOR                          LCD_STR_THERMOMETER _UxGT(" Фактор")
#define MSG_AUTOTEMP                        _UxGT("Автотемпература")
#define MSG_ON                              _UxGT("Вкл. ")
#define MSG_OFF                             _UxGT("Откл. ")
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("Выбор")
#define MSG_ACC                             _UxGT("Ускорение")
#define MSG_JERK                            _UxGT("Рывок")
#define MSG_VX_JERK                         _UxGT("Vx-рывок")
#define MSG_VY_JERK                         _UxGT("Vy-рывок")
#define MSG_VZ_JERK                         _UxGT("Vz-рывок")
#define MSG_VE_JERK                         _UxGT("Ve-рывок")
#define MSG_VELOCITY                        _UxGT("Скорость")
#define MSG_VMAX                            _UxGT("Vмакс ")
#define MSG_VMIN                            _UxGT("Vмин")
#define MSG_VTRAV_MIN                       _UxGT("Vпутеш. мин")
#define MSG_ACCELERATION                    _UxGT("Ускорение")
#define MSG_AMAX                            _UxGT("Aмакс")
#define MSG_A_RETRACT                       _UxGT("A-втягивание")
#define MSG_A_TRAVEL                        _UxGT("A-путеш.")
#define MSG_STEPS_PER_MM                    _UxGT("Шаг/мм")
#define MSG_XSTEPS                          _UxGT("X шаг/мм")
#define MSG_YSTEPS                          _UxGT("Y шаг/мм")
#define MSG_ZSTEPS                          _UxGT("Z шаг/мм")
#define MSG_ESTEPS                          _UxGT("E шаг/мм")
#define MSG_E1STEPS                         _UxGT("E1 шаг/мм")
#define MSG_E2STEPS                         _UxGT("E2 шаг/мм")
#define MSG_E3STEPS                         _UxGT("E3 шаг/мм")
#define MSG_E4STEPS                         _UxGT("E4 шаг/мм")
#define MSG_E5STEPS                         _UxGT("E5 шаг/мм")
#define MSG_TEMPERATURE                     _UxGT("Температура")
#define MSG_MOTION                          _UxGT("Механика")
#define MSG_FILAMENT                        _UxGT("Пластик")
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E в mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("Диаметр пластика")
#define MSG_ADVANCE_K                       _UxGT("K продвижения")
#define MSG_CONTRAST                        _UxGT("Контраст LCD")
#define MSG_STORE_EEPROM                    _UxGT("Сохранить в EEPROM")
#define MSG_LOAD_EEPROM                     _UxGT("Загрузить из EEPROM")
#define MSG_RESTORE_FAILSAFE                _UxGT("Сброс EEPROM")
#define MSG_INIT_EEPROM                     _UxGT("Инициализ. EEPROM")
#define MSG_REFRESH                         _UxGT("Обновить")
#define MSG_WATCH                           _UxGT("ГЛАВНЫЙ ЭКРАН")
#define MSG_PREPARE                         _UxGT("УПРАВЛЕНИЕ")
#define MSG_TUNE                            _UxGT("НАСТРОЙКИ")
#define MSG_PAUSE_PRINT                     _UxGT("ПАУЗА")
#define MSG_RESUME_PRINT                    _UxGT("ПРОДОЛЖИТЬ")
#define MSG_STOP_PRINT                      _UxGT("ОСТАНОВИТЬ ПЕЧАТЬ")
#define MSG_CARD_MENU                       _UxGT("КАРТА ПАМЯТИ")
#define MSG_NO_CARD                         _UxGT("Карта не установлена")
#define MSG_DWELL                           _UxGT("Бездействие...")
#define MSG_USERWAIT                        _UxGT("Продолжить")
#define MSG_PRINT_PAUSED                    _UxGT("Печать приостановлена")
#define MSG_RESUMING                        _UxGT("Возобновление печати...")
#define MSG_PRINT_ABORTED                   _UxGT("Печать прекращена")
#define MSG_NO_MOVE                         _UxGT("Перемещения заблокированы")
#define MSG_KILLED                          _UxGT("ПЕЧАТЬ ПРЕРВАНА")
#define MSG_STOPPED                         _UxGT("ПЕЧАТЬ ОСТАНОВЛЕНА")
#define MSG_CONTROL_RETRACT                 _UxGT("Втягивание mm")
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("Втягивание смены mm")
#define MSG_CONTROL_RETRACTF                _UxGT("Втягивание V")
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("Втягивание подъема mm")
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("Возврат mm")
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("Возврат смены mm")
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("Возврат V")
#define MSG_AUTORETRACT                     _UxGT("Втягивание автоматич.")
#define MSG_FILAMENTCHANGE                  _UxGT("Смена пластика")
#define MSG_INIT_SDCARD                     _UxGT("Инициализация карты памяти")
#define MSG_CNG_SDCARD                      _UxGT("Смена карты памяти")
#define MSG_ZPROBE_OUT                      _UxGT("Z датчик за пределами стола")
#define MSG_BLTOUCH                         _UxGT("Датчик BLTouch")
#define MSG_BLTOUCH_SELFTEST                _UxGT("Проверка работоспособ. BLTouch")
#define MSG_BLTOUCH_RESET                   _UxGT("Сброс BLTouch")
#define MSG_BLTOUCH_DEPLOY                  _UxGT("Разместить BLTouch")
#define MSG_BLTOUCH_STOW                    _UxGT("Рабочее положение BLTouch")
#define MSG_HOME                            _UxGT("Движение в нулевую точку")
#define MSG_FIRST                           _UxGT("первый")
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Смещение датчика по Z")
#define MSG_BABYSTEP_X                      _UxGT("Микрошаг X")
#define MSG_BABYSTEP_Y                      _UxGT("Микрошаг Y")
#define MSG_BABYSTEP_Z                      _UxGT("Микрошаг Z")
#define MSG_ENDSTOP_ABORT                   _UxGT("Сработал концевик")
#define MSG_HEATING_FAILED_LCD              _UxGT("СБОЙ ПРИ НАГРЕВЕ!!!")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("Ошибка вторич. датчика Т")
#define MSG_THERMAL_RUNAWAY                 _UxGT("УТЕЧКА ТЕПЛА!!!")
#define MSG_ERR_MAXTEMP                     _UxGT("Ошибка: Т макс.")
#define MSG_ERR_MINTEMP                     _UxGT("Ошибка: Т мин.")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("Ошибка: Т макс. стол")
#define MSG_ERR_MINTEMP_BED                 _UxGT("Ошибка: Т мин. стол")
#define MSG_ERR_Z_HOMING                    _UxGT("Ошибка возврата по Z")
#define MSG_HALTED                          _UxGT("ОСТАНОВ!!!")
#define MSG_PLEASE_RESET                    _UxGT("Нажмите кнопку сброса")
#define MSG_SHORT_DAY                       _UxGT("д") // One character only
#define MSG_SHORT_HOUR                      _UxGT("ч") // One character only
#define MSG_SHORT_MINUTE                    _UxGT("м") // One character only
#define MSG_HEATING                         _UxGT("Нагрев хотэнда...")
#define MSG_BED_HEATING                     _UxGT("Нагрев стола...")
#define MSG_BED_DONE                        _UxGT("Нагрев стола выполнен")
#define MSG_HEATING_COMPLETE                _UxGT("Нагрев выполнен")
#define MSG_DELTA_CALIBRATE                 _UxGT("Калибровка Delta")
#define MSG_DELTA_CALIBRATE_X               _UxGT("Калибровать X")
#define MSG_DELTA_CALIBRATE_Y               _UxGT("Калибровать Y")
#define MSG_DELTA_CALIBRATE_Z               _UxGT("Калибровать Z")
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("Калибровать центр")
#define MSG_DELTA_SETTINGS                  _UxGT("Пок. настройки Delta")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("Авто калибровка")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("Задать высоту Delta")
#define MSG_INFO_MENU                       _UxGT("Информация о принтере")
#define MSG_INFO_PRINTER_MENU               _UxGT("ИНФОРМАЦИЯ О ПРИНТЕРЕ")
#define MSG_3POINT_LEVELING                 _UxGT("Выравнивание по 3-м точкам")
#define MSG_LINEAR_LEVELING                 _UxGT("Выравнивание линейное")
#define MSG_BILINEAR_LEVELING               _UxGT("Выравнивание билинейное")
#define MSG_UBL_LEVELING                    _UxGT("Выравнивание UBL")
#define MSG_MESH_LEVELING                   _UxGT("Выравнивание по сеткам")
#define MSG_INFO_STATS_MENU                 _UxGT("Статистика принтера")
#define MSG_INFO_BOARD_MENU                 _UxGT("Системная плата")
#define MSG_INFO_THERMISTOR_MENU            _UxGT("Термодатчики")
#define MSG_INFO_EXTRUDERS                  _UxGT("Экструдеры")
#define MSG_INFO_BAUDRATE                   _UxGT("Скорость обмена")
#define MSG_INFO_PROTOCOL                   _UxGT("Протокол обмена")
#define MSG_CASE_LIGHT                      _UxGT("Освещение")
#define MSG_CASE_LIGHT_BRIGHTNESS           _UxGT("Яркость освещения")
#if LCD_WIDTH >= 20
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Закончено")
  #define MSG_INFO_PRINT_TIME               _UxGT("Полное время печати")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Израсходовано пластика")
#else
  #define MSG_INFO_PRINT_COUNT              _UxGT("Отпечатков")
  #define MSG_INFO_COMPLETED_PRINTS         _UxGT("Закончено")
  #define MSG_INFO_PRINT_TIME               _UxGT("Всего")
  #define MSG_INFO_PRINT_LONGEST            _UxGT("Наибольшее")
  #define MSG_INFO_PRINT_FILAMENT           _UxGT("Израсходовано пластика")
#endif
#define MSG_INFO_MIN_TEMP                   _UxGT("Мин. Т")
#define MSG_INFO_MAX_TEMP                   _UxGT("Макс. Т")
#define MSG_INFO_PSU                        _UxGT("Блок питания")
#define MSG_DRIVE_STRENGTH                  _UxGT("Сила привода")
#define MSG_DAC_PERCENT                     _UxGT("DAC %")
#define MSG_DAC_EEPROM_WRITE                _UxGT("Запись DAC EEPROM")
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("ЗАМЕНА ПЛАСТИКА")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("Опции:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("Выдавливание пластика")
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("Возобновление печати")
#define MSG_FILAMENT_CHANGE_MINTEMP         _UxGT("Мин. температура")
#define MSG_FILAMENT_CHANGE_NOZZLE          _UxGT(" хотэнда: ")
//
// Filament Change screens show up to 3 lines on a 4-line display
//                        ...or up to 2 lines on a 3-line display
//
#if LCD_HEIGHT >= 4
  #define MSG_FILAMENT_CHANGE_INIT_1      _UxGT("Ожидается")
  #define MSG_FILAMENT_CHANGE_INIT_2      _UxGT("начало операции")
  #define MSG_FILAMENT_CHANGE_INIT_3      _UxGT("смены пластика")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1    _UxGT("Ожидается")
  #define MSG_FILAMENT_CHANGE_UNLOAD_2    _UxGT("выгрузка пластика")
  #define MSG_FILAMENT_CHANGE_INSERT_1    _UxGT("Ожидается ")
  #define MSG_FILAMENT_CHANGE_INSERT_2    _UxGT("установка пластика")
  #define MSG_FILAMENT_CHANGE_INSERT_3    _UxGT("...")
  #define MSG_FILAMENT_CHANGE_HEAT_1      _UxGT("Нажмите кнопку для")
  #define MSG_FILAMENT_CHANGE_HEAT_2      _UxGT("нагрева хотэнда...")
  #define MSG_FILAMENT_CHANGE_HEATING_1   _UxGT("Нагрев хотэнда")
  #define MSG_FILAMENT_CHANGE_HEATING_2   _UxGT("Идет нагрев...")
  #define MSG_FILAMENT_CHANGE_LOAD_1      _UxGT("Ожидается")
  #define MSG_FILAMENT_CHANGE_LOAD_2      _UxGT("установка пластика")
  #define MSG_FILAMENT_CHANGE_RESUME_1    _UxGT("Ожидается")
  #define MSG_FILAMENT_CHANGE_RESUME_2    _UxGT("возобновление")
#else // LCD_HEIGHT < 4
  #define MSG_FILAMENT_CHANGE_INIT_1      _UxGT("Ожидайте...")
  #define MSG_FILAMENT_CHANGE_UNLOAD_1    _UxGT("Выгрузите...")
  #define MSG_FILAMENT_CHANGE_INSERT_1    _UxGT("Установите...")
  #define MSG_FILAMENT_CHANGE_HEATING_1   _UxGT("Нагрев...")
  #define MSG_FILAMENT_CHANGE_LOAD_1      _UxGT("Загрузка...")
  #define MSG_FILAMENT_CHANGE_EXTRUDE_1   _UxGT("Выдавливание...")
  #define MSG_FILAMENT_CHANGE_RESUME_1    _UxGT("Возобновление...")
#endif // LCD_HEIGHT < 4

#endif // LANGUAGE_RU_H
